name: scroll_master
description: An example showing how to handle common scrolling gesture conflicts in Flutter
version: 2.0.0+1

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pedantic: ^1.11.0
  oktoast: ^3.0.0
  get: ^4.6.1
  flutter_hooks: ^0.18.2+1
  custom_nested_scroll_view:
    git:
      url: https://github.com/idootop/custom_nested_scroll_view.git

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/
