name: scroll_master
description: >
  A Flutter example showcasing efficient resolution of scrolling conflicts. 
  It demonstrates features like pull-to-refresh for NestedScrollView, synchronized scrolling for ScrollView and TabView, and other enhancements.
version: 3.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  nested_scroll_view_plus:
    git:
      url: https://github.com/idootop/nested_scroll_view_plus.git

  get: ^4.6.6
  flutter_hooks: ^0.20.3

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
